default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>

development:
  <<: *default
  database: consultorios_development
  user: postgres
  password: <%= ENV['POSTGRES_ENV_POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: consultorios_test
  user: postgres
  password: <%= ENV['POSTGRES_ENV_POSTGRES_PASSWORD'] %>

production:
  <<: *default
  database: consultorios_production
  user: postgres
  password: <%= ENV['POSTGRES_ENV_POSTGRES_PASSWORD'] %>
